// https://nuxt.com/docs/api/configuration/nuxt-config

// IDs aus .env (lokal) bzw. GitHub-Secrets (CI) – Hinweis: der Env-Var-Name
// enthält einen Tippfehler (GOOFLE statt GOOGLE) – bitte in GitHub Secrets
// genauso hinterlegen wie in .env
const gtagId = process.env.GOOGLE_ANALYTICS_MEAS_ID || 'G-XXXXXXXXXX'
const adsensePubId = process.env.GOOGLE_ADSENSE_PUB_ID
  ? `ca-${process.env.GOOGLE_ADSENSE_PUB_ID}`
  : 'ca-pub-XXXXXXXXXXXXXXXX'

// giscus – IDs aus .env (lokal) bzw. GitHub Vars (CI)
// Zu ermitteln auf https://giscus.app/de nach Eingabe des Repos
const giscusRepoId = process.env.GISCUS_REPO_ID || 'R_kgDOSNCPlg'
const giscusCategoryId = process.env.GISCUS_CATEGORY_ID || 'DIC_kwDOSNCPls4C7zVP'

export default defineNuxtConfig({
  modules: [
    './modules/generate-taxonomy',
    '@nuxt/content',
    '@nuxtjs/tailwindcss',
    'nuxt-gtag',
  ],

  // Macht adsensePubId und Slot-IDs zur Laufzeit in allen Komponenten via useRuntimeConfig() verfügbar
  // Slot-IDs sind öffentlich und werden fest eingecheckt (kein Secret)
  runtimeConfig: {
    public: {
      adsensePubId,
      adsenseSlots: {
        left:      '3478648998', // the78mole-content-left
        right:     '9230728617', // the78mole-content-right
        bottom:    '8012270852', // the78mole-content-bottom
        inArticle: '5913240643', // the78mole-content-inarticle
      },
      giscus: {
        repo:       'the78mole-blog/the78mole-blog.github.io',
        repoId:     giscusRepoId,
        category:   'Blog Comments',
        categoryId: giscusCategoryId,
      },
    },
  },

  gtag: {
    id: gtagId,
    // Consent Mode v2: Script immer laden, Consent standardmäßig verweigert (DSGVO).
    // Daten werden erst gesendet, nachdem der Nutzer im ConsentBanner zugestimmt hat.
    initCommands: [
      ['consent', 'default', {
        analytics_storage:   'denied',
        ad_storage:          'denied',
        ad_user_data:        'denied',
        ad_personalization:  'denied',
        wait_for_update:     500,
      }],
    ],
  },

  app: {
    head: {
      link: [
        { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' },
      ],
    },
  },

  tailwindcss: {
    // Prevents the HMR loop caused by Tailwind watching its own output
    viewer: false,
  },

  vite: {
    build: {
      // Suppress the nuxt:module-preload-polyfill sourcemap warning
      sourcemap: false,
    },
  },

  content: {
    build: {
      markdown: {
        highlight: {
          theme: 'github-dark',
          langs: [
            'bash', 'c', 'cpp', 'css', 'dockerfile', 'go', 'html',
            'java', 'javascript', 'json', 'makefile', 'markdown',
            'python', 'rust', 'shell', 'sql', 'toml', 'typescript',
            'vim', 'xml', 'yaml',
          ],
        },
      },
    },
  },

  compatibilityDate: '2024-11-01',

  // Redirects von alten WordPress-Permalinks (/:slug) auf neue Nuxt-Routen
  // GitHub Pages hat keinen Server – Nuxt generiert statische Meta-Refresh-Seiten
  routeRules: {
    // --- Seiten ---
    '/about':                     { redirect: '/pages/about' },
    '/about/':                    { redirect: '/pages/about' },
    '/contact':                   { redirect: '/pages/contact' },
    '/contact/':                  { redirect: '/pages/contact' },
    '/links':                     { redirect: '/pages/links' },
    '/links/':                    { redirect: '/pages/links' },
    '/projects':                  { redirect: '/pages/projects' },
    '/projects/':                 { redirect: '/pages/projects' },
    '/tutorials':                 { redirect: '/pages/tutorials' },
    '/tutorials/':                { redirect: '/pages/tutorials' },
    '/impressum':                 { redirect: '/pages/impressum' },
    '/impressum/':                { redirect: '/pages/impressum' },
    '/datenschutzerklaerung':     { redirect: '/pages/datenschutzerklaerung' },
    '/datenschutzerklaerung/':    { redirect: '/pages/datenschutzerklaerung' },
    '/projects/km271-wifi-howto':  { redirect: '/pages/km271-wifi-howto' },
    '/projects/km271-wifi-howto/': { redirect: '/pages/km271-wifi-howto' },

    // --- Blog-Posts ---
    '/angular-web-app-on-esp32':                          { redirect: '/blog/2021/angular-web-app-on-esp32' },
    '/angular-web-app-on-esp32/':                         { redirect: '/blog/2021/angular-web-app-on-esp32' },
    '/atlassian-and-new-ssl-certificates':                { redirect: '/blog/2018/atlassian-and-new-ssl-certificates' },
    '/atlassian-and-new-ssl-certificates/':               { redirect: '/blog/2018/atlassian-and-new-ssl-certificates' },
    '/code-red-on-fire-or-heat-metering-with-node-red':   { redirect: '/blog/2023/code-red-on-fire-or-heat-metering-with-node-red' },
    '/code-red-on-fire-or-heat-metering-with-node-red/':  { redirect: '/blog/2023/code-red-on-fire-or-heat-metering-with-node-red' },
    '/compile-ceph-mimic-on-arm-32-bit':                  { redirect: '/blog/2019/compile-ceph-mimic-on-arm-32-bit' },
    '/compile-ceph-mimic-on-arm-32-bit/':                 { redirect: '/blog/2019/compile-ceph-mimic-on-arm-32-bit' },
    '/compiling-software-on-ram-limited-multi-core-systems':  { redirect: '/blog/2019/compiling-software-on-ram-limited-multi-core-systems' },
    '/compiling-software-on-ram-limited-multi-core-systems/': { redirect: '/blog/2019/compiling-software-on-ram-limited-multi-core-systems' },
    '/crying-on-open-waters-a-piece-of-hw-for-ahoydtu-and-reading-the-hoymiles-inverters':   { redirect: '/blog/2023/crying-on-open-waters-a-piece-of-hw-for-ahoydtu-and-reading-the-hoymiles-inverters' },
    '/crying-on-open-waters-a-piece-of-hw-for-ahoydtu-and-reading-the-hoymiles-inverters/':  { redirect: '/blog/2023/crying-on-open-waters-a-piece-of-hw-for-ahoydtu-and-reading-the-hoymiles-inverters' },
    '/digging':                   { redirect: '/blog/2018/digging' },
    '/digging/':                  { redirect: '/blog/2018/digging' },
    '/doing-the-undone-decoding-sml-or-hacking-the-tibber-raw-data':   { redirect: '/blog/2023/doing-the-undone-decoding-sml-or-hacking-the-tibber-raw-data' },
    '/doing-the-undone-decoding-sml-or-hacking-the-tibber-raw-data/':  { redirect: '/blog/2023/doing-the-undone-decoding-sml-or-hacking-the-tibber-raw-data' },
    '/doxygen-tips-and-tricks':   { redirect: '/blog/2020/doxygen-tips-and-tricks' },
    '/doxygen-tips-and-tricks/':  { redirect: '/blog/2020/doxygen-tips-and-tricks' },
    '/eex-epex-spot-and-the-real-net-intransparency':   { redirect: '/blog/2021/eex-epex-spot-and-the-real-net-intransparency' },
    '/eex-epex-spot-and-the-real-net-intransparency/':  { redirect: '/blog/2021/eex-epex-spot-and-the-real-net-intransparency' },
    '/esp32-evb-and-platform-io-yet-another-esp32-tutorial':   { redirect: '/blog/2020/esp32-evb-and-platform-io-yet-another-esp32-tutorial' },
    '/esp32-evb-and-platform-io-yet-another-esp32-tutorial/':  { redirect: '/blog/2020/esp32-evb-and-platform-io-yet-another-esp32-tutorial' },
    '/esp32-evb-platformio-and-esp-idf-yet-another-esp32-tutorial':   { redirect: '/blog/2021/esp32-evb-platformio-and-esp-idf-yet-another-esp32-tutorial' },
    '/esp32-evb-platformio-and-esp-idf-yet-another-esp32-tutorial/':  { redirect: '/blog/2021/esp32-evb-platformio-and-esp-idf-yet-another-esp32-tutorial' },
    '/freertos-debugging-on-stm32-cpu-usage':   { redirect: '/blog/2020/freertos-debugging-on-stm32-cpu-usage' },
    '/freertos-debugging-on-stm32-cpu-usage/':  { redirect: '/blog/2020/freertos-debugging-on-stm32-cpu-usage' },
    '/fresh-air-for-mole-holes-dyson-floor-nozzle-revived':   { redirect: '/blog/2025/fresh-air-for-mole-holes-dyson-floor-nozzle-revived' },
    '/fresh-air-for-mole-holes-dyson-floor-nozzle-revived/':  { redirect: '/blog/2025/fresh-air-for-mole-holes-dyson-floor-nozzle-revived' },
    '/get-the-hell-out-of-my-wall-box-or-how-to-make-cheap-type-2-adapter-cables-not-so-sticky':   { redirect: '/blog/2021/get-the-hell-out-of-my-wall-box-or-how-to-make-cheap-type-2-adapter-cables-not-so-sticky' },
    '/get-the-hell-out-of-my-wall-box-or-how-to-make-cheap-type-2-adapter-cables-not-so-sticky/':  { redirect: '/blog/2021/get-the-hell-out-of-my-wall-box-or-how-to-make-cheap-type-2-adapter-cables-not-so-sticky' },
    '/getting-rid-of-nasty-underground-neighbours-iot-mouse-trap':   { redirect: '/blog/2024/getting-rid-of-nasty-underground-neighbours-iot-mouse-trap' },
    '/getting-rid-of-nasty-underground-neighbours-iot-mouse-trap/':  { redirect: '/blog/2024/getting-rid-of-nasty-underground-neighbours-iot-mouse-trap' },
    '/getting-started-embedded-part-ii-the-embeded-project':   { redirect: '/blog/2018/getting-started-embedded-part-ii-the-embeded-project' },
    '/getting-started-embedded-part-ii-the-embeded-project/':  { redirect: '/blog/2018/getting-started-embedded-part-ii-the-embeded-project' },
    '/getting-started-embedded-part-i-the-toolchain':   { redirect: '/blog/2018/getting-started-embedded-part-i-the-toolchain' },
    '/getting-started-embedded-part-i-the-toolchain/':  { redirect: '/blog/2018/getting-started-embedded-part-i-the-toolchain' },
    '/get-your-personal-oil-well-level-integrating-oilfox-into-home-assistant-using-node-red':   { redirect: '/blog/2021/get-your-personal-oil-well-level-integrating-oilfox-into-home-assistant-using-node-red' },
    '/get-your-personal-oil-well-level-integrating-oilfox-into-home-assistant-using-node-red/':  { redirect: '/blog/2021/get-your-personal-oil-well-level-integrating-oilfox-into-home-assistant-using-node-red' },
    '/google-chromecasts-smartphone-independance-day':   { redirect: '/blog/2018/google-chromecasts-smartphone-independance-day' },
    '/google-chromecasts-smartphone-independance-day/':  { redirect: '/blog/2018/google-chromecasts-smartphone-independance-day' },
    '/headless-rescue-system-over-ssh':   { redirect: '/blog/2019/headless-rescue-system-over-ssh' },
    '/headless-rescue-system-over-ssh/':  { redirect: '/blog/2019/headless-rescue-system-over-ssh' },
    '/how-to-build-a-private-storage-cluster-with-ceph':   { redirect: '/blog/2019/how-to-build-a-private-storage-cluster-with-ceph' },
    '/how-to-build-a-private-storage-cluster-with-ceph/':  { redirect: '/blog/2019/how-to-build-a-private-storage-cluster-with-ceph' },
    '/how-to-build-a-smart-home':   { redirect: '/blog/2019/how-to-build-a-smart-home' },
    '/how-to-build-a-smart-home/':  { redirect: '/blog/2019/how-to-build-a-smart-home' },
    '/how-to-debug-hardware-faults-on-your-dedicated-server':   { redirect: '/blog/2020/how-to-debug-hardware-faults-on-your-dedicated-server' },
    '/how-to-debug-hardware-faults-on-your-dedicated-server/':  { redirect: '/blog/2020/how-to-debug-hardware-faults-on-your-dedicated-server' },
    '/how-to-open-your-zipper-use-fuse-to-browse-archives':   { redirect: '/blog/2021/how-to-open-your-zipper-use-fuse-to-browse-archives' },
    '/how-to-open-your-zipper-use-fuse-to-browse-archives/':  { redirect: '/blog/2021/how-to-open-your-zipper-use-fuse-to-browse-archives' },
    '/how-to-wire-up-an-ev-wall-box':   { redirect: '/blog/2021/how-to-wire-up-an-ev-wall-box' },
    '/how-to-wire-up-an-ev-wall-box/':  { redirect: '/blog/2021/how-to-wire-up-an-ev-wall-box' },
    '/installing-bigbluebutton-on-your-dedicated-server':   { redirect: '/blog/2020/installing-bigbluebutton-on-your-dedicated-server' },
    '/installing-bigbluebutton-on-your-dedicated-server/':  { redirect: '/blog/2020/installing-bigbluebutton-on-your-dedicated-server' },
    '/integrating-wmbus-devices-into-iobroker':   { redirect: '/blog/2019/integrating-wmbus-devices-into-iobroker' },
    '/integrating-wmbus-devices-into-iobroker/':  { redirect: '/blog/2019/integrating-wmbus-devices-into-iobroker' },
    '/just-another-hobby-3d-printing':   { redirect: '/blog/2020/just-another-hobby-3d-printing' },
    '/just-another-hobby-3d-printing/':  { redirect: '/blog/2020/just-another-hobby-3d-printing' },
    '/just-do-it-how-to-create-your-own-home-assistant-add-on-part-1':   { redirect: '/blog/2021/just-do-it-how-to-create-your-own-home-assistant-add-on-part-1' },
    '/just-do-it-how-to-create-your-own-home-assistant-add-on-part-1/':  { redirect: '/blog/2021/just-do-it-how-to-create-your-own-home-assistant-add-on-part-1' },
    '/kathrein-exip-418-getting-it-back-to-work-on-ubiquity-networks':   { redirect: '/blog/2021/kathrein-exip-418-getting-it-back-to-work-on-ubiquity-networks' },
    '/kathrein-exip-418-getting-it-back-to-work-on-ubiquity-networks/':  { redirect: '/blog/2021/kathrein-exip-418-getting-it-back-to-work-on-ubiquity-networks' },
    '/limiting-ev-charge-soc-with-go-echarger-and-home-assistant':   { redirect: '/blog/2021/limiting-ev-charge-soc-with-go-echarger-and-home-assistant' },
    '/limiting-ev-charge-soc-with-go-echarger-and-home-assistant/':  { redirect: '/blog/2021/limiting-ev-charge-soc-with-go-echarger-and-home-assistant' },
    '/mbus-application-layer':   { redirect: '/blog/2023/mbus-application-layer' },
    '/mbus-application-layer/':  { redirect: '/blog/2023/mbus-application-layer' },
    '/merging-the-contents-of-two-influxdbs':   { redirect: '/blog/2019/merging-the-contents-of-two-influxdbs' },
    '/merging-the-contents-of-two-influxdbs/':  { redirect: '/blog/2019/merging-the-contents-of-two-influxdbs' },
    '/modbus-rj45-breakout':   { redirect: '/blog/2023/modbus-rj45-breakout' },
    '/modbus-rj45-breakout/':  { redirect: '/blog/2023/modbus-rj45-breakout' },
    '/moles-heating-system':   { redirect: '/blog/2022/moles-heating-system' },
    '/moles-heating-system/':  { redirect: '/blog/2022/moles-heating-system' },
    '/onewire-immersed':   { redirect: '/blog/2022/onewire-immersed' },
    '/onewire-immersed/':  { redirect: '/blog/2022/onewire-immersed' },
    '/orangepi-2g-iot-android-sdk':   { redirect: '/blog/2018/orangepi-2g-iot-android-sdk' },
    '/orangepi-2g-iot-android-sdk/':  { redirect: '/blog/2018/orangepi-2g-iot-android-sdk' },
    '/orangepi-4g-iot-android-8-1-sdk':   { redirect: '/blog/2018/orangepi-4g-iot-android-8-1-sdk' },
    '/orangepi-4g-iot-android-8-1-sdk/':  { redirect: '/blog/2018/orangepi-4g-iot-android-8-1-sdk' },
    '/orangepi-4g-iot-complete-pack':   { redirect: '/blog/2019/orangepi-4g-iot-complete-pack' },
    '/orangepi-4g-iot-complete-pack/':  { redirect: '/blog/2019/orangepi-4g-iot-complete-pack' },
    '/penmount-pci-touch-controllers-and-i2c-lost-in-space':   { redirect: '/blog/2020/penmount-pci-touch-controllers-and-i2c-lost-in-space' },
    '/penmount-pci-touch-controllers-and-i2c-lost-in-space/':  { redirect: '/blog/2020/penmount-pci-touch-controllers-and-i2c-lost-in-space' },
    '/pushing-the-rectangle-through-the-round-develop-with-riot-os-on-windows-doing-the-impossible':   { redirect: '/blog/2022/pushing-the-rectangle-through-the-round-develop-with-riot-os-on-windows-doing-the-impossible' },
    '/pushing-the-rectangle-through-the-round-develop-with-riot-os-on-windows-doing-the-impossible/':  { redirect: '/blog/2022/pushing-the-rectangle-through-the-round-develop-with-riot-os-on-windows-doing-the-impossible' },
    '/reading-a-meter-speaking-mbus':   { redirect: '/blog/2023/reading-a-meter-speaking-mbus' },
    '/reading-a-meter-speaking-mbus/':  { redirect: '/blog/2023/reading-a-meter-speaking-mbus' },
    '/reverse-engineering-the-buderus-km217':   { redirect: '/blog/2021/reverse-engineering-the-buderus-km217' },
    '/reverse-engineering-the-buderus-km217/':  { redirect: '/blog/2021/reverse-engineering-the-buderus-km217' },
    '/schools-out-how-to-tame-your-children':   { redirect: '/blog/2020/schools-out-how-to-tame-your-children' },
    '/schools-out-how-to-tame-your-children/':  { redirect: '/blog/2020/schools-out-how-to-tame-your-children' },
    '/smart-home-controlled-joy-it-lab-power-supply':   { redirect: '/blog/2023/smart-home-controlled-joy-it-lab-power-supply' },
    '/smart-home-controlled-joy-it-lab-power-supply/':  { redirect: '/blog/2023/smart-home-controlled-joy-it-lab-power-supply' },
    '/some-thoughs-on-the-m-bus':   { redirect: '/blog/2022/some-thoughs-on-the-m-bus' },
    '/some-thoughs-on-the-m-bus/':  { redirect: '/blog/2022/some-thoughs-on-the-m-bus' },
    '/sorting-your-digital-mess-how-to-easily-set-up-a-private-search-engine':   { redirect: '/blog/2021/sorting-your-digital-mess-how-to-easily-set-up-a-private-search-engine' },
    '/sorting-your-digital-mess-how-to-easily-set-up-a-private-search-engine/':  { redirect: '/blog/2021/sorting-your-digital-mess-how-to-easily-set-up-a-private-search-engine' },
    '/stm32-bldc-motor-control':   { redirect: '/blog/2019/stm32-bldc-motor-control' },
    '/stm32-bldc-motor-control/':  { redirect: '/blog/2019/stm32-bldc-motor-control' },
    '/stm32cubemx-and-sdram':   { redirect: '/blog/2020/stm32cubemx-and-sdram' },
    '/stm32cubemx-and-sdram/':  { redirect: '/blog/2020/stm32cubemx-and-sdram' },
    '/stm32-freertos-and-printf-with-floats':   { redirect: '/blog/2020/stm32-freertos-and-printf-with-floats' },
    '/stm32-freertos-and-printf-with-floats/':  { redirect: '/blog/2020/stm32-freertos-and-printf-with-floats' },
    '/stm32-uart-continuous-receive-with-interrupt':   { redirect: '/blog/2019/stm32-uart-continuous-receive-with-interrupt' },
    '/stm32-uart-continuous-receive-with-interrupt/':  { redirect: '/blog/2019/stm32-uart-continuous-receive-with-interrupt' },
    '/stm32-usb-dfu':   { redirect: '/blog/2020/stm32-usb-dfu' },
    '/stm32-usb-dfu/':  { redirect: '/blog/2020/stm32-usb-dfu' },
    '/taking-your-m-bus-online-with-mqtt':   { redirect: '/blog/2021/taking-your-m-bus-online-with-mqtt' },
    '/taking-your-m-bus-online-with-mqtt/':  { redirect: '/blog/2021/taking-your-m-bus-online-with-mqtt' },
    '/taming-the-cephodian-octopus-or-quincy':   { redirect: '/blog/2023/taming-the-cephodian-octopus-or-quincy' },
    '/taming-the-cephodian-octopus-or-quincy/':  { redirect: '/blog/2023/taming-the-cephodian-octopus-or-quincy' },
    '/the-great-flood-how-i-turned-my-living-room-into-a-high-tech-sump-pit':   { redirect: '/blog/2025/the-great-flood-how-i-turned-my-living-room-into-a-high-tech-sump-pit' },
    '/the-great-flood-how-i-turned-my-living-room-into-a-high-tech-sump-pit/':  { redirect: '/blog/2025/the-great-flood-how-i-turned-my-living-room-into-a-high-tech-sump-pit' },
    '/the-magic-of-absolute-humidity':   { redirect: '/blog/2021/the-magic-of-absolute-humidity' },
    '/the-magic-of-absolute-humidity/':  { redirect: '/blog/2021/the-magic-of-absolute-humidity' },
    '/the-remote-serial-debugging-nightmare':   { redirect: '/blog/2022/the-remote-serial-debugging-nightmare' },
    '/the-remote-serial-debugging-nightmare/':  { redirect: '/blog/2022/the-remote-serial-debugging-nightmare' },
    '/think-sustainable-thnk-city-reanimated-work-in-progress':   { redirect: '/blog/2021/think-sustainable-thnk-city-reanimated-work-in-progress' },
    '/think-sustainable-thnk-city-reanimated-work-in-progress/':  { redirect: '/blog/2021/think-sustainable-thnk-city-reanimated-work-in-progress' },
    '/ultrasound-distance-module-overview':   { redirect: '/blog/2021/ultrasound-distance-module-overview' },
    '/ultrasound-distance-module-overview/':  { redirect: '/blog/2021/ultrasound-distance-module-overview' },
    '/windows-was-just-a-pain':   { redirect: '/blog/2018/windows-was-just-a-pain' },
    '/windows-was-just-a-pain/':  { redirect: '/blog/2018/windows-was-just-a-pain' },
    '/wmbus-meters-and-how-to-get-it-into-home-assistant':   { redirect: '/blog/2021/wmbus-meters-and-how-to-get-it-into-home-assistant' },
    '/wmbus-meters-and-how-to-get-it-into-home-assistant/':  { redirect: '/blog/2021/wmbus-meters-and-how-to-get-it-into-home-assistant' },

    // =========================================================================
    // Redirects für Google Search Console Coverage-Fehler (2026-05-21)
    // Alle alten WordPress-Archiv-, Tag-, Kategorie- und Feed-URLs werden auf
    // sinnvolle Zielseiten umgeleitet. wp-content/uploads → /uploads korrigiert.
    // =========================================================================

    // --- Tag-Archivseiten ---
    '/tag/thnk-city':               { redirect: '/tags?tag=thnk-city' },
    '/tag/thnk-city/':              { redirect: '/tags?tag=thnk-city' },
    '/tag/open-semantic-search':    { redirect: '/tags?tag=open-semantic-search' },
    '/tag/open-semantic-search/':   { redirect: '/tags?tag=open-semantic-search' },
    '/tag/ssl':                     { redirect: '/tags?tag=ssl' },
    '/tag/ssl/':                    { redirect: '/tags?tag=ssl' },
    '/tag/bash':                    { redirect: '/tags?tag=bash' },
    '/tag/bash/':                   { redirect: '/tags?tag=bash' },
    '/tag/cluster':                 { redirect: '/tags?tag=cluster' },
    '/tag/cluster/':                { redirect: '/tags?tag=cluster' },
    '/tag/influxdb':                { redirect: '/tags?tag=influxdb' },
    '/tag/influxdb/':               { redirect: '/tags?tag=influxdb' },
    '/tag/hal':                     { redirect: '/tags?tag=hal' },
    '/tag/hal/':                    { redirect: '/tags?tag=hal' },
    '/tag/hal/feed':                { redirect: '/tags?tag=hal' },
    '/tag/hal/feed/':               { redirect: '/tags?tag=hal' },
    '/tag/compressed-archives':     { redirect: '/tags?tag=compressed-archives' },
    '/tag/compressed-archives/':    { redirect: '/tags?tag=compressed-archives' },
    '/tag/stromboerse':             { redirect: '/tags?tag=stromboerse' },
    '/tag/stromboerse/':            { redirect: '/tags?tag=stromboerse' },
    '/tag/sml':                     { redirect: '/tags?tag=sml' },
    '/tag/sml/':                    { redirect: '/tags?tag=sml' },
    '/tag/pio':                     { redirect: '/tags?tag=pio' },
    '/tag/pio/':                    { redirect: '/tags?tag=pio' },
    '/tag/pio/feed':                { redirect: '/tags?tag=pio' },
    '/tag/pio/feed/':               { redirect: '/tags?tag=pio' },
    '/tag/soil':                    { redirect: '/tags?tag=soil' },
    '/tag/soil/':                   { redirect: '/tags?tag=soil' },
    '/tag/dtu':                     { redirect: '/tags?tag=dtu' },
    '/tag/dtu/':                    { redirect: '/tags?tag=dtu' },
    '/tag/dtu/feed':                { redirect: '/tags?tag=dtu' },
    '/tag/dtu/feed/':               { redirect: '/tags?tag=dtu' },
    '/tag/usb':                     { redirect: '/tags?tag=usb' },
    '/tag/usb/':                    { redirect: '/tags?tag=usb' },
    '/tag/market-data':             { redirect: '/tags?tag=market-data' },
    '/tag/market-data/':            { redirect: '/tags?tag=market-data' },
    '/tag/run-time-analysis':       { redirect: '/tags?tag=run-time-analysis' },
    '/tag/run-time-analysis/':      { redirect: '/tags?tag=run-time-analysis' },
    '/tag/electric-vehicle':        { redirect: '/tags?tag=electric-vehicle' },
    '/tag/electric-vehicle/':       { redirect: '/tags?tag=electric-vehicle' },
    '/tag/rd6006':                  { redirect: '/tags?tag=rd6006' },
    '/tag/rd6006/':                 { redirect: '/tags?tag=rd6006' },
    '/tag/rd6006/feed':             { redirect: '/tags?tag=rd6006' },
    '/tag/rd6006/feed/':            { redirect: '/tags?tag=rd6006' },
    '/tag/mbus':                    { redirect: '/tags?tag=mbus' },
    '/tag/mbus/':                   { redirect: '/tags?tag=mbus' },
    '/tag/isolated-modbus':         { redirect: '/tags?tag=isolated-modbus' },
    '/tag/isolated-modbus/':        { redirect: '/tags?tag=isolated-modbus' },
    '/tag/isolated-modbus/feed':    { redirect: '/tags?tag=isolated-modbus' },
    '/tag/isolated-modbus/feed/':   { redirect: '/tags?tag=isolated-modbus' },
    '/tag/add-on-repository':       { redirect: '/tags?tag=add-on-repository' },
    '/tag/add-on-repository/':      { redirect: '/tags?tag=add-on-repository' },
    '/tag/rd6012':                  { redirect: '/tags?tag=rd6012' },
    '/tag/rd6012/':                 { redirect: '/tags?tag=rd6012' },
    '/tag/rd6012/feed':             { redirect: '/tags?tag=rd6012' },
    '/tag/rd6012/feed/':            { redirect: '/tags?tag=rd6012' },
    '/tag/debugging':               { redirect: '/tags?tag=debugging' },
    '/tag/debugging/':              { redirect: '/tags?tag=debugging' },
    '/tag/km200':                   { redirect: '/tags?tag=km200' },
    '/tag/km200/':                  { redirect: '/tags?tag=km200' },
    '/tag/km200/feed':              { redirect: '/tags?tag=km200' },
    '/tag/km200/feed/':             { redirect: '/tags?tag=km200' },
    '/tag/pm2204':                  { redirect: '/tags?tag=pm2204' },
    '/tag/pm2204/':                 { redirect: '/tags?tag=pm2204' },
    '/tag/nodered':                 { redirect: '/tags?tag=nodered' },
    '/tag/nodered/':                { redirect: '/tags?tag=nodered' },
    '/tag/bldc':                    { redirect: '/tags?tag=bldc' },
    '/tag/bldc/':                   { redirect: '/tags?tag=bldc' },
    '/tag/bldc/feed':               { redirect: '/tags?tag=bldc' },
    '/tag/bldc/feed/':              { redirect: '/tags?tag=bldc' },
    '/tag/exip':                    { redirect: '/tags?tag=exip' },
    '/tag/exip/':                   { redirect: '/tags?tag=exip' },
    '/tag/ultrasonic':              { redirect: '/tags?tag=ultrasonic' },
    '/tag/ultrasonic/':             { redirect: '/tags?tag=ultrasonic' },
    '/tag/electric-car':            { redirect: '/tags?tag=electric-car' },
    '/tag/electric-car/':           { redirect: '/tags?tag=electric-car' },
    '/tag/bootloader':              { redirect: '/tags?tag=bootloader' },
    '/tag/bootloader/':             { redirect: '/tags?tag=bootloader' },
    '/tag/touch-controller':        { redirect: '/tags?tag=touch-controller' },
    '/tag/touch-controller/':       { redirect: '/tags?tag=touch-controller' },
    '/tag/olimex':                  { redirect: '/tags?tag=olimex' },
    '/tag/olimex/':                 { redirect: '/tags?tag=olimex' },
    '/tag/olimex/feed':             { redirect: '/tags?tag=olimex' },
    '/tag/olimex/feed/':            { redirect: '/tags?tag=olimex' },
    '/tag/vscode':                  { redirect: '/tags?tag=vscode' },
    '/tag/vscode/':                 { redirect: '/tags?tag=vscode' },
    '/tag/stm32cubeide':            { redirect: '/tags?tag=stm32cubeide' },
    '/tag/stm32cubeide/':           { redirect: '/tags?tag=stm32cubeide' },
    '/tag/penmount':                { redirect: '/tags?tag=penmount' },
    '/tag/penmount/':               { redirect: '/tags?tag=penmount' },
    '/tag/stm32':                   { redirect: '/tags?tag=stm32' },
    '/tag/stm32/':                  { redirect: '/tags?tag=stm32' },
    '/tag/stm32/feed':              { redirect: '/tags?tag=stm32' },
    '/tag/stm32/feed/':             { redirect: '/tags?tag=stm32' },
    '/tag/iobroker':                { redirect: '/tags?tag=iobroker' },
    '/tag/iobroker/':               { redirect: '/tags?tag=iobroker' },
    '/tag/iobroker/feed':           { redirect: '/tags?tag=iobroker' },
    '/tag/iobroker/feed/':          { redirect: '/tags?tag=iobroker' },
    '/tag/touch-screen':            { redirect: '/tags?tag=touch-screen' },
    '/tag/touch-screen/':           { redirect: '/tags?tag=touch-screen' },
    '/tag/odroid-hc4':              { redirect: '/tags?tag=odroid-hc4' },
    '/tag/odroid-hc4/':             { redirect: '/tags?tag=odroid-hc4' },
    '/tag/opensemanticsearch':      { redirect: '/tags?tag=opensemanticsearch' },
    '/tag/opensemanticsearch/':     { redirect: '/tags?tag=opensemanticsearch' },
    '/tag/m-bus':                   { redirect: '/tags?tag=m-bus' },
    '/tag/m-bus/':                  { redirect: '/tags?tag=m-bus' },
    '/tag/codenotary':              { redirect: '/tags?tag=codenotary' },
    '/tag/codenotary/':             { redirect: '/tags?tag=codenotary' },

    // --- Kategorie-Archivseiten ---
    '/category/laboratory':                       { redirect: '/categories?category=laboratory' },
    '/category/laboratory/':                      { redirect: '/categories?category=laboratory' },
    '/category/tibber':                           { redirect: '/categories?category=tibber' },
    '/category/tibber/':                          { redirect: '/categories?category=tibber' },
    '/category/tibber/feed':                      { redirect: '/categories?category=tibber' },
    '/category/tibber/feed/':                     { redirect: '/categories?category=tibber' },
    '/category/renewable-energy/solar-energy':    { redirect: '/categories?category=renewable-energy' },
    '/category/renewable-energy/solar-energy/':   { redirect: '/categories?category=renewable-energy' },
    '/category/esp32/esphome':                    { redirect: '/categories?category=esp32' },
    '/category/esp32/esphome/':                   { redirect: '/categories?category=esp32' },
    '/category/esp32/esphome/feed':               { redirect: '/categories?category=esp32' },
    '/category/esp32/esphome/feed/':              { redirect: '/categories?category=esp32' },
    '/category/esp32':                            { redirect: '/categories?category=esp32' },
    '/category/esp32/':                           { redirect: '/categories?category=esp32' },
    '/category/esp32/feed':                       { redirect: '/categories?category=esp32' },
    '/category/esp32/feed/':                      { redirect: '/categories?category=esp32' },
    '/category/smart-home/page/2':                { redirect: '/categories?category=smart-home' },
    '/category/smart-home/page/2/':               { redirect: '/categories?category=smart-home' },
    '/category/general':                          { redirect: '/categories?category=general' },
    '/category/general/':                         { redirect: '/categories?category=general' },
    '/category/freertos':                         { redirect: '/categories?category=freertos' },
    '/category/freertos/':                        { redirect: '/categories?category=freertos' },
    '/category/arm/page/2':                       { redirect: '/categories?category=arm' },
    '/category/arm/page/2/':                      { redirect: '/categories?category=arm' },
    '/category/tools/atlassian':                  { redirect: '/categories?category=tools' },
    '/category/tools/atlassian/':                 { redirect: '/categories?category=tools' },
    '/category/smart-home/node-red':              { redirect: '/categories?category=smart-home' },
    '/category/smart-home/node-red/':             { redirect: '/categories?category=smart-home' },
    '/category/bus-systems/modbus':               { redirect: '/categories?category=bus-systems' },
    '/category/bus-systems/modbus/':              { redirect: '/categories?category=bus-systems' },
    '/category/bus-systems/modbus/feed':          { redirect: '/categories?category=bus-systems' },
    '/category/bus-systems/modbus/feed/':         { redirect: '/categories?category=bus-systems' },
    '/category/stm32/motor-control':              { redirect: '/categories?category=stm32' },
    '/category/stm32/motor-control/':             { redirect: '/categories?category=stm32' },
    '/category/corona-virus':                     { redirect: '/categories?category=corona-virus' },
    '/category/corona-virus/':                    { redirect: '/categories?category=corona-virus' },
    '/category/uncategorized/page/2':             { redirect: '/categories?category=uncategorized' },
    '/category/uncategorized/page/2/':            { redirect: '/categories?category=uncategorized' },

    // --- Datumsarchive ---
    '/2023/02':  { redirect: '/' },
    '/2023/02/': { redirect: '/' },
    '/2022/01':  { redirect: '/' },
    '/2022/01/': { redirect: '/' },
    '/page/2':   { redirect: '/' },
    '/page/2/':  { redirect: '/' },
    '/page/7':   { redirect: '/' },
    '/page/7/':  { redirect: '/' },

    // --- Post-Feed-URLs → jeweiliger Blog-Post ---
    '/wmbus-meters-and-how-to-get-it-into-home-assistant/feed':   { redirect: '/blog/2021/wmbus-meters-and-how-to-get-it-into-home-assistant' },
    '/wmbus-meters-and-how-to-get-it-into-home-assistant/feed/':  { redirect: '/blog/2021/wmbus-meters-and-how-to-get-it-into-home-assistant' },
    '/installing-bigbluebutton-on-your-dedicated-server/feed':    { redirect: '/blog/2020/installing-bigbluebutton-on-your-dedicated-server' },
    '/installing-bigbluebutton-on-your-dedicated-server/feed/':   { redirect: '/blog/2020/installing-bigbluebutton-on-your-dedicated-server' },
    '/crying-on-open-waters-a-piece-of-hw-for-ahoydtu-and-reading-the-hoymiles-inverters/feed':   { redirect: '/blog/2023/crying-on-open-waters-a-piece-of-hw-for-ahoydtu-and-reading-the-hoymiles-inverters' },
    '/crying-on-open-waters-a-piece-of-hw-for-ahoydtu-and-reading-the-hoymiles-inverters/feed/':  { redirect: '/blog/2023/crying-on-open-waters-a-piece-of-hw-for-ahoydtu-and-reading-the-hoymiles-inverters' },
    '/freertos-debugging-on-stm32-cpu-usage/feed':        { redirect: '/blog/2020/freertos-debugging-on-stm32-cpu-usage' },
    '/freertos-debugging-on-stm32-cpu-usage/feed/':       { redirect: '/blog/2020/freertos-debugging-on-stm32-cpu-usage' },
    '/onewire-immersed/feed':                             { redirect: '/blog/2022/onewire-immersed' },
    '/onewire-immersed/feed/':                            { redirect: '/blog/2022/onewire-immersed' },
    '/doxygen-tips-and-tricks/feed':                      { redirect: '/blog/2020/doxygen-tips-and-tricks' },
    '/doxygen-tips-and-tricks/feed/':                     { redirect: '/blog/2020/doxygen-tips-and-tricks' },
    '/taming-the-cephodian-octopus-or-quincy/feed':       { redirect: '/blog/2023/taming-the-cephodian-octopus-or-quincy' },
    '/taming-the-cephodian-octopus-or-quincy/feed/':      { redirect: '/blog/2023/taming-the-cephodian-octopus-or-quincy' },
    '/smart-home-controlled-joy-it-lab-power-supply/feed':   { redirect: '/blog/2023/smart-home-controlled-joy-it-lab-power-supply' },
    '/smart-home-controlled-joy-it-lab-power-supply/feed/':  { redirect: '/blog/2023/smart-home-controlled-joy-it-lab-power-supply' },
    '/reading-a-meter-speaking-mbus/feed':                { redirect: '/blog/2023/reading-a-meter-speaking-mbus' },
    '/reading-a-meter-speaking-mbus/feed/':               { redirect: '/blog/2023/reading-a-meter-speaking-mbus' },
    '/esp32-evb-platformio-and-esp-idf-yet-another-esp32-tutorial/feed':   { redirect: '/blog/2021/esp32-evb-platformio-and-esp-idf-yet-another-esp32-tutorial' },
    '/esp32-evb-platformio-and-esp-idf-yet-another-esp32-tutorial/feed/':  { redirect: '/blog/2021/esp32-evb-platformio-and-esp-idf-yet-another-esp32-tutorial' },
    '/stm32-bldc-motor-control/feed':                     { redirect: '/blog/2019/stm32-bldc-motor-control' },
    '/stm32-bldc-motor-control/feed/':                    { redirect: '/blog/2019/stm32-bldc-motor-control' },
    '/how-to-debug-hardware-faults-on-your-dedicated-server/feed':   { redirect: '/blog/2020/how-to-debug-hardware-faults-on-your-dedicated-server' },
    '/how-to-debug-hardware-faults-on-your-dedicated-server/feed/':  { redirect: '/blog/2020/how-to-debug-hardware-faults-on-your-dedicated-server' },
    '/orangepi-2g-iot-android-sdk/feed':                  { redirect: '/blog/2018/orangepi-2g-iot-android-sdk' },
    '/orangepi-2g-iot-android-sdk/feed/':                 { redirect: '/blog/2018/orangepi-2g-iot-android-sdk' },
    '/projects/km271-wifi-howto/feed':                    { redirect: '/pages/km271-wifi-howto' },
    '/projects/km271-wifi-howto/feed/':                   { redirect: '/pages/km271-wifi-howto' },
    '/eex-epex-spot-and-the-real-net-intransparency/feed':   { redirect: '/blog/2021/eex-epex-spot-and-the-real-net-intransparency' },
    '/eex-epex-spot-and-the-real-net-intransparency/feed/':  { redirect: '/blog/2021/eex-epex-spot-and-the-real-net-intransparency' },
    '/getting-rid-of-nasty-underground-neighbours-iot-mouse-trap/feed':   { redirect: '/blog/2024/getting-rid-of-nasty-underground-neighbours-iot-mouse-trap' },
    '/getting-rid-of-nasty-underground-neighbours-iot-mouse-trap/feed/':  { redirect: '/blog/2024/getting-rid-of-nasty-underground-neighbours-iot-mouse-trap' },
    '/angular-web-app-on-esp32/feed':                     { redirect: '/blog/2021/angular-web-app-on-esp32' },
    '/angular-web-app-on-esp32/feed/':                    { redirect: '/blog/2021/angular-web-app-on-esp32' },
    '/limiting-ev-charge-soc-with-go-echarger-and-home-assistant/feed':   { redirect: '/blog/2021/limiting-ev-charge-soc-with-go-echarger-and-home-assistant' },
    '/limiting-ev-charge-soc-with-go-echarger-and-home-assistant/feed/':  { redirect: '/blog/2021/limiting-ev-charge-soc-with-go-echarger-and-home-assistant' },
    '/integrating-wmbus-devices-into-iobroker/feed':      { redirect: '/blog/2019/integrating-wmbus-devices-into-iobroker' },
    '/integrating-wmbus-devices-into-iobroker/feed/':     { redirect: '/blog/2019/integrating-wmbus-devices-into-iobroker' },
    '/taking-your-m-bus-online-with-mqtt/feed':           { redirect: '/blog/2021/taking-your-m-bus-online-with-mqtt' },
    '/taking-your-m-bus-online-with-mqtt/feed/':          { redirect: '/blog/2021/taking-your-m-bus-online-with-mqtt' },
    '/stm32-freertos-and-printf-with-floats/feed':        { redirect: '/blog/2020/stm32-freertos-and-printf-with-floats' },
    '/stm32-freertos-and-printf-with-floats/feed/':       { redirect: '/blog/2020/stm32-freertos-and-printf-with-floats' },
    '/how-to-open-your-zipper-use-fuse-to-browse-archives/feed':   { redirect: '/blog/2021/how-to-open-your-zipper-use-fuse-to-browse-archives' },
    '/how-to-open-your-zipper-use-fuse-to-browse-archives/feed/':  { redirect: '/blog/2021/how-to-open-your-zipper-use-fuse-to-browse-archives' },

    // --- WordPress-Upload-Dateien: wp-content/uploads → /uploads ---
    '/wp-content/uploads/2023/03/KM217-WiFi.pdf':            { redirect: '/uploads/2023/03/KM217-WiFi.pdf' },
    '/wp-content/uploads/2023/03/KM217-WiFi-PCB-0.0.6.pdf':  { redirect: '/uploads/2023/03/KM217-WiFi-PCB-0.0.6.pdf' },
    '/wp-content/uploads/2022/11/ibom.html':                 { redirect: '/uploads/2022/11/ibom.html' },
    '/wp-content/uploads/2021/10/aWATTar_prices.json':       { redirect: '/uploads/2021/10/aWATTar_prices.json' },

    // --- WordPress-Plugin-Pfade → Home ---
    '/wp-content/plugins/code-syntax-block':   { redirect: '/' },
    '/wp-content/plugins/code-syntax-block/':  { redirect: '/' },

    // --- Spezialfälle ---
    '/tutorials/creating-custom-issue-types-in-jira':    { redirect: '/pages/tutorials' },
    '/tutorials/creating-custom-issue-types-in-jira/':   { redirect: '/pages/tutorials' },
    '/mbus-application-layer/the78mole.de/reading-a-meter-speaking-mbus': { redirect: '/blog/2023/reading-a-meter-speaking-mbus' },

    // -----------------------------------------------------------------------
    // Aus Google-Analytics-Coverage-Report 2026-05-22 ergänzt.
    // NICHT ENTFERNEN – diese Pfade wurden von Google gecrawlt und müssen
    // dauerhaft mit einem sinnvollen Redirect versehen bleiben.
    // -----------------------------------------------------------------------

    // --- fehlende /tag/* Weiterleitungen ------------------------------------
    '/tag/atlassian/feed':                         { redirect: '/tags?tag=atlassian' },
    '/tag/atlassian/feed/':                        { redirect: '/tags?tag=atlassian' },
    '/tag/buderus-lm-2107':                        { redirect: '/tags?tag=buderus-lm-2107' },
    '/tag/buderus-lm-2107/':                       { redirect: '/tags?tag=buderus-lm-2107' },
    '/tag/clean-code':                             { redirect: '/tags?tag=clean-code' },
    '/tag/clean-code/':                            { redirect: '/tags?tag=clean-code' },
    '/tag/cubemx':                                 { redirect: '/tags?tag=cubemx' },
    '/tag/cubemx/':                                { redirect: '/tags?tag=cubemx' },
    '/tag/digital-classroom':                      { redirect: '/tags?tag=digital-classroom' },
    '/tag/digital-classroom/':                     { redirect: '/tags?tag=digital-classroom' },
    '/tag/digital-classroom/feed':                 { redirect: '/tags?tag=digital-classroom' },
    '/tag/digital-classroom/feed/':                { redirect: '/tags?tag=digital-classroom' },
    '/tag/doxygen':                                { redirect: '/tags?tag=doxygen' },
    '/tag/doxygen/':                               { redirect: '/tags?tag=doxygen' },
    '/tag/epex':                                   { redirect: '/tags?tag=epex' },
    '/tag/epex/':                                  { redirect: '/tags?tag=epex' },
    '/tag/epex-spot':                              { redirect: '/tags?tag=epex-spot' },
    '/tag/epex-spot/':                             { redirect: '/tags?tag=epex-spot' },
    '/tag/esphome':                                { redirect: '/tags?tag=esphome' },
    '/tag/esphome/':                               { redirect: '/tags?tag=esphome' },
    '/tag/firmware-upgrade':                       { redirect: '/tags?tag=firmware-upgrade' },
    '/tag/firmware-upgrade/':                      { redirect: '/tags?tag=firmware-upgrade' },
    '/tag/freertos':                               { redirect: '/tags?tag=freertos' },
    '/tag/freertos/':                              { redirect: '/tags?tag=freertos' },
    '/tag/hc4':                                    { redirect: '/tags?tag=hc4' },
    '/tag/hc4/':                                   { redirect: '/tags?tag=hc4' },
    '/tag/iot':                                    { redirect: '/tags?tag=iot' },
    '/tag/iot/':                                   { redirect: '/tags?tag=iot' },
    '/tag/joy-it':                                 { redirect: '/tags?tag=joy-it' },
    '/tag/joy-it/':                                { redirect: '/tags?tag=joy-it' },
    '/tag/km271':                                  { redirect: '/tags?tag=km271' },
    '/tag/km271/':                                 { redirect: '/tags?tag=km271' },
    '/tag/linux':                                  { redirect: '/tags?tag=linux' },
    '/tag/linux/':                                 { redirect: '/tags?tag=linux' },
    '/tag/locamatic-web':                          { redirect: '/tags?tag=locamatic-web' },
    '/tag/locamatic-web/':                         { redirect: '/tags?tag=locamatic-web' },
    '/tag/logamatic-2107':                         { redirect: '/tags?tag=logamatic-2107' },
    '/tag/logamatic-2107/':                        { redirect: '/tags?tag=logamatic-2107' },
    '/tag/migration':                              { redirect: '/tags?tag=migration' },
    '/tag/migration/':                             { redirect: '/tags?tag=migration' },
    '/tag/renault-zoe':                            { redirect: '/tags?tag=renault-zoe' },
    '/tag/renault-zoe/':                           { redirect: '/tags?tag=renault-zoe' },
    '/tag/renault-zoe-soc-limit-charging':         { redirect: '/tags?tag=renault-zoe-soc-limit-charging' },
    '/tag/renault-zoe-soc-limit-charging/':        { redirect: '/tags?tag=renault-zoe-soc-limit-charging' },
    '/tag/rtos':                                   { redirect: '/tags?tag=rtos' },
    '/tag/rtos/':                                  { redirect: '/tags?tag=rtos' },
    '/tag/serial-console':                         { redirect: '/tags?tag=serial-console' },
    '/tag/serial-console/':                        { redirect: '/tags?tag=serial-console' },
    '/tag/ssh':                                    { redirect: '/tags?tag=ssh' },
    '/tag/ssh/':                                   { redirect: '/tags?tag=ssh' },
    '/tag/streamserver':                           { redirect: '/tags?tag=streamserver' },
    '/tag/streamserver/':                          { redirect: '/tags?tag=streamserver' },
    '/tag/strompreise':                            { redirect: '/tags?tag=strompreise' },
    '/tag/strompreise/':                           { redirect: '/tags?tag=strompreise' },
    '/tag/think-city':                             { redirect: '/tags?tag=think-city' },
    '/tag/think-city/':                            { redirect: '/tags?tag=think-city' },
    '/tag/uart':                                   { redirect: '/tags?tag=uart' },
    '/tag/uart/':                                  { redirect: '/tags?tag=uart' },
    '/tag/virus':                                  { redirect: '/tags?tag=virus' },
    '/tag/virus/':                                 { redirect: '/tags?tag=virus' },

    // --- fehlende /category/* Weiterleitungen --------------------------------
    '/category/bus-systems/wmbus':                 { redirect: '/categories?category=wmbus' },
    '/category/bus-systems/wmbus/':                { redirect: '/categories?category=wmbus' },
    '/category/laboratory/controlled-devices':     { redirect: '/categories?category=laboratory' },
    '/category/laboratory/controlled-devices/':    { redirect: '/categories?category=laboratory' },
    '/category/os/android':                        { redirect: '/categories' },
    '/category/os/android/':                       { redirect: '/categories' },
    '/category/windows':                           { redirect: '/categories?category=windows' },
    '/category/windows/':                          { redirect: '/categories?category=windows' },

    // --- fehlende /post-slug/feed/ Weiterleitungen ---------------------------
    '/compile-ceph-mimic-on-arm-32-bit/feed':                             { redirect: '/blog/2019/compile-ceph-mimic-on-arm-32-bit' },
    '/compile-ceph-mimic-on-arm-32-bit/feed/':                            { redirect: '/blog/2019/compile-ceph-mimic-on-arm-32-bit' },
    '/getting-started-embedded-part-ii-the-embeded-project/feed':         { redirect: '/blog/2018/getting-started-embedded-part-ii-the-embeded-project' },
    '/getting-started-embedded-part-ii-the-embeded-project/feed/':        { redirect: '/blog/2018/getting-started-embedded-part-ii-the-embeded-project' },
    '/stm32-usb-dfu/feed':                                                 { redirect: '/blog/2020/stm32-usb-dfu' },
    '/stm32-usb-dfu/feed/':                                                { redirect: '/blog/2020/stm32-usb-dfu' },

    // --- Datum-Archiv-Seiten (WP) → entsprechende Blog-Archive-Seite --------
    '/2021/07':  { redirect: '/2021/07' },
    '/2021/07/': { redirect: '/2021/07' },
    '/2023/04':  { redirect: '/2023/04' },
    '/2023/04/': { redirect: '/2023/04' },
  },
  devtools: { enabled: true },
})
