<script setup lang="ts">
// Prevent Vue from auto-forwarding `class` (which carries the shiki classes)
// onto the outer wrapper div. We forward it explicitly to <pre> instead,
// so that the selectors `html pre.shiki code .sXxx { --shiki-default: ... }`
// generated by @nuxt/content match correctly.
defineOptions({ inheritAttrs: false })

const props = defineProps<{
  code?: string
  language?: string
  filename?: string
  highlights?: number[]
  meta?: string
  class?: string
}>()

const copied = ref(false)
const containerRef = ref<HTMLElement | null>(null)

async function copyCode() {
  const codeEl = containerRef.value?.querySelector('code')
  const text = codeEl?.innerText ?? ''
  await navigator.clipboard.writeText(text)
  copied.value = true
  setTimeout(() => { copied.value = false }, 2000)
}
</script>

<template>
  <div ref="containerRef" class="relative group my-4">
    <button
      class="
        absolute right-2 top-2 z-10
        opacity-0 group-hover:opacity-100
        transition-opacity duration-150
        bg-gray-700 hover:bg-gray-600
        text-gray-300 hover:text-white
        p-1.5 rounded
        select-none
      "
      :aria-label="copied ? 'Copied!' : 'Copy code'"
      @click="copyCode"
    >
      <!-- Checkmark (copied state) -->
      <svg v-if="copied" xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
        <polyline points="20 6 9 17 4 12" />
      </svg>
      <!-- Clipboard copy icon (default state) -->
      <svg v-else xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
        <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
        <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
      </svg>
    </button>

    <pre :class="['!my-0', props.class]"><slot /></pre>
  </div>
</template>
